title: "Partner Resources"
author: Microsoft
description: Resources created by Microsoft's GPS (Global Partner Solutions) team
baseurl: "/PartnerResources"

back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2024 Microsoft"

# Social (First three Required)
repo: "https://github.com/microsoft/PartnerResources"
github_user: "microsoft"
github_repo: "PartnerResources"
github_branch: "main"
twitter: microsoft
linkedin: microsoft

logo_pixels: 34
color: "#0078D4" # Azure Blue

# show related plans on learning plans
showrelatedplans: true

# include app insights
includeappinsights: true

accentColor: "#0078D4" # Azure Blue
themeColor: "#0078D4" # Azure Blue
fixedNav: 'true' # true or false

last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

permalink: /:year/:title/
markdown: kramdown
exclude: [_site, CHANGELOG.md, LICENSE, README.md]

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path

# Defaults
defaults:
  - scope:
      path: "_docs"
      type: "docs"
    values:
      layout: page
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

relative_links:
  enabled: true
  collections: true

plugins:
  - jekyll-redirect-from
  - jekyll-relative-links